# Generated by Django 4.2.21 on 2025-05-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departament',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, unique=True, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'job',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Lastname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Salary', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Salario')),
                ('Email', models.EmailField(max_length=50, verbose_name='Email')),
                ('Direction', models.CharField(max_length=100, verbose_name='Direccion')),
                ('Birthdate', models.DateField(verbose_name='Fecha de nacimento')),
                ('Cellphone', models.CharField(max_length=50, verbose_name='Celular')),
                ('Departament', models.ManyToManyField(to='anthony_zambrano.departament')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anthony_zambrano.job', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'employed',
                'ordering': ['id'],
            },
        ),
    ]
