# Generated by Django 4.2.21 on 2025-05-28 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'Type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=10, unique=True, verbose_name='cedula')),
                ('Name', models.CharField(max_length=50, verbose_name='nombre')),
                ('Lastname', models.CharField(max_length=50, verbose_name='apellido')),
                ('Age', models.PositiveIntegerField(default=0, verbose_name='edad')),
                ('Salary', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='salario')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='fecha_creacion')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, verbose_name='fecha_modificacion')),
                ('category', models.ManyToManyField(to='clientes.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.type', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'person',
                'ordering': ['id'],
            },
        ),
    ]
